# ion example: Concurrent Workflow Graph

version: 2

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:16.4.2


      steps:
      
      - run: npm install
      - run: npm test
        